/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticasDePrivacidadRouteImport } from './routes/politicas-de-privacidad'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOnlineUsersRouteImport } from './routes/api/online-users'
import { Route as NegocioIdRouteImport } from './routes/negocio/$id'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiBusinessesIndexRouteImport } from './routes/api/businesses/index'
import { Route as ApiBusinessesIdRouteImport } from './routes/api/businesses/$id'
import { Route as ApiBusinessesMeRouteImport } from './routes/api/businesses/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasDePrivacidadRoute = PoliticasDePrivacidadRouteImport.update({
  id: '/politicas-de-privacidad',
  path: '/politicas-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnlineUsersRoute = ApiOnlineUsersRouteImport.update({
  id: '/api/online-users',
  path: '/api/online-users',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioIdRoute = NegocioIdRouteImport.update({
  id: '/negocio/$id',
  path: '/negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesIndexRoute = ApiBusinessesIndexRouteImport.update({
  id: '/api/businesses/',
  path: '/api/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesIdRoute = ApiBusinessesIdRouteImport.update({
  id: '/api/businesses/$id',
  path: '/api/businesses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesMeRoute = ApiBusinessesMeRouteImport.update({
  id: '/api/businesses/me',
  path: '/api/businesses/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/online-users': typeof ApiOnlineUsersRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/businesses/$id': typeof ApiBusinessesIdRoute
  '/api/businesses/me': typeof ApiBusinessesMeRoute
  '/api/businesses/': typeof ApiBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/online-users': typeof ApiOnlineUsersRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/businesses/$id': typeof ApiBusinessesIdRoute
  '/api/businesses/me': typeof ApiBusinessesMeRoute
  '/api/businesses': typeof ApiBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/online-users': typeof ApiOnlineUsersRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/businesses/$id': typeof ApiBusinessesIdRoute
  '/api/businesses/me': typeof ApiBusinessesMeRoute
  '/api/businesses/': typeof ApiBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politicas-de-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/online-users'
    | '/negocio/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/businesses/$id'
    | '/api/businesses/me'
    | '/api/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politicas-de-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/online-users'
    | '/negocio/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/businesses/$id'
    | '/api/businesses/me'
    | '/api/businesses'
  id:
    | '__root__'
    | '/'
    | '/politicas-de-privacidad'
    | '/quienes-somos'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/online-users'
    | '/negocio/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/businesses/$id'
    | '/api/businesses/me'
    | '/api/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticasDePrivacidadRoute: typeof PoliticasDePrivacidadRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOnlineUsersRoute: typeof ApiOnlineUsersRoute
  NegocioIdRoute: typeof NegocioIdRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiBusinessesIdRoute: typeof ApiBusinessesIdRoute
  ApiBusinessesMeRoute: typeof ApiBusinessesMeRoute
  ApiBusinessesIndexRoute: typeof ApiBusinessesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-de-privacidad': {
      id: '/politicas-de-privacidad'
      path: '/politicas-de-privacidad'
      fullPath: '/politicas-de-privacidad'
      preLoaderRoute: typeof PoliticasDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/online-users': {
      id: '/api/online-users'
      path: '/api/online-users'
      fullPath: '/api/online-users'
      preLoaderRoute: typeof ApiOnlineUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$id': {
      id: '/negocio/$id'
      path: '/negocio/$id'
      fullPath: '/negocio/$id'
      preLoaderRoute: typeof NegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses/': {
      id: '/api/businesses/'
      path: '/api/businesses'
      fullPath: '/api/businesses/'
      preLoaderRoute: typeof ApiBusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses/$id': {
      id: '/api/businesses/$id'
      path: '/api/businesses/$id'
      fullPath: '/api/businesses/$id'
      preLoaderRoute: typeof ApiBusinessesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses/me': {
      id: '/api/businesses/me'
      path: '/api/businesses/me'
      fullPath: '/api/businesses/me'
      preLoaderRoute: typeof ApiBusinessesMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticasDePrivacidadRoute: PoliticasDePrivacidadRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOnlineUsersRoute: ApiOnlineUsersRoute,
  NegocioIdRoute: NegocioIdRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiBusinessesIdRoute: ApiBusinessesIdRoute,
  ApiBusinessesMeRoute: ApiBusinessesMeRoute,
  ApiBusinessesIndexRoute: ApiBusinessesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
